apiVersion: v1
data:
  config.yml: "---\ncluster_name: \"Kubernetes Cluster\"\nimages:\n  ok: \"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Yes_check.svg/200px-Yes_check.svg.png\"\n
    \ warn: \"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Dialog-warning.svg/200px-Dialog-warning.svg.png\"\n
    \ progress: \"https://i.gifer.com/80ZN.gif\"\nreceivers:\n  slack: \n    cluster_ops:\n
    \     channel: \"#test\"\n      token: \"{SLACK_TOKEN}\"\n  flowdock:\n    cluster_ops:\n
    \     token: \"{FLOWDOCK_TOKEN}\"\n"
kind: ConfigMap
metadata:
  name: kube-lookout
  labels:
    app: kube-lookout
  namespace: kube-lookout
